title:        Alan Duvall
tagline:      "Don't lose your happiness on the pursuit for more"
description:  'Follow me at <a href="https://twitter.com/famousalan" target="_blank">@famousalan</a>.'
url:          http://alanduvall.com
version:      1.1.1
author:
  name:       ''
  email:      ''
#markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
